### ISSUE TITLE
Python 3.6 does not have datetime.fromisoformat

### ISSUE THREAD

**Issue by atotoun** [precice/EventTimings#10]
```
Traceback (most recent call last):
  File "events2trace.py", line 155, in <module>
    main()
  File "events2trace.py", line 117, in main
    jsons = normalize_times(*jsons)
  File "events2trace.py", line 69, in normalize_times
    minT = min([datetime.datetime.fromisoformat(d["Initialized"]) for d in args])
  File "events2trace.py", line 69, in <listcomp>
    minT = min([datetime.datetime.fromisoformat(d["Initialized"]) for d in args])
AttributeError: type object 'datetime.datetime' has no attribute 'fromisoformat'
```

**Comment by KonnikPahoni** [comment]
Indeed!

**Comment by dapickMS** [comment]
Why this issue was closed? was there a fix for it?

**Comment by floli** [comment]
Please have a lock at the linked commit https://github.com/precice/EventTimings/commit/7cf5b06693bef98486a5391e05358a543fab4e3e 

It was fixed / replaced by a workaround. Do you have any problems?

**Comment by dapickMS** [comment]
Thanks! The workaround works well.
